modulo1/git/redes-sociais.txt
=> minhas redes sociais

modulo1/git/filmes.txt
=> filmes que já olhei no Netflix

modulo1/git/musicas.txt
=> coloquei os estilos de musica que eu gosto

modulo1/projeto-readme/aprendizados.md
- Muito boas as aulas da Labenu
=> coloquei o resumo da semana

modulo1/variaveis/index.html, modulo1/variaveis/index.js
=> atividade variaveis

modulo1/operadores/index.html, modulo1/operadores/index.js
=>  entrada da atividade sobre operadores

modulo1/strings-arrays/index.html, modulo1/strings-arrays/index.js
=> tarefas de strings-arrays

modulo1/condicionais/index.html, modulo1/condicionais/index.js
=> atividades de condicionais

modulo1/lacos/index.html, modulo1/lacos/index.js
=> atividades de lacos

modulo1/projeto-blackjack/desafio.js, modulo1/projeto-blackjack/index.html, modulo1/projeto-blackjack/naoMexer.js, modulo1/projeto-blackjack/nossoJogo.js
=> projeto de sexta 2

modulo1/funcoes-de-array/index.html, modulo1/funcoes-de-array/index.js
=> atividades callback e funcoes arrays

modulo2/props-labedin/labedin/package-lock.json
=> projeto props-labedin

modulo2/estados-insta4/insta4/package-lock.json, modulo2/estados-insta4/insta4/src/App.js, modulo2/estados-insta4/insta4/src/components/Post/Post.js
- Botão de adicionar funciona e deixa o input limpo depois em adicionar.
- o input de busca 
https://quiet-breath.surge.sh/
###Exercícios do CodeSanbox
https://codesandbox.io/s/exemplos-listas-estado-forked-xwx5c?file=/src/components/Exemplo8.js
=> projeto insta4 com adiconar

modulo2/postman/Labefy.postman_collection.json
=> atividade de api

modulo4/intro-typescript/package-lock.json, modulo4/intro-typescript/package.json, modulo4/intro-typescript/src/index.ts, modulo4/intro-typescript/src/index2.ts, modulo4/intro-typescript/src/index3.ts, modulo4/intro-typescript/src/index4.ts, modulo4/intro-typescript/src/index5.ts, modulo4/intro-typescript/tsconfig.json
=> atividade de typescript

modulo4/aprofundamento-typescript/package-lock.json, modulo4/aprofundamento-typescript/package.json, modulo4/aprofundamento-typescript/src/exercicio-4.ts, modulo4/aprofundamento-typescript/src/index.ts, modulo4/aprofundamento-typescript/src/index2.ts, modulo4/aprofundamento-typescript/src/index3.ts, modulo4/aprofundamento-typescript/src/index5.ts, modulo4/aprofundamento-typescript/src/tsconfig.json, modulo4/aprofundamento-typescript/tsconfig.json
=> atividades aprofundamento-typescript

modulo4/intro-express/package-lock.json, modulo4/intro-express/package.json, modulo4/intro-express/tsconfig.json, modulo4/introExpress/.gitignore, modulo4/introExpress/package.json, modulo4/introExpress/src/data.ts, modulo4/introExpress/src/index.ts, modulo4/introExpress/tsconfig.json
=> atividade express

modulo3/projeto-labex/projeto-labex/src/pages/AdminHome/AdminHomePage.js, modulo3/projeto-labex/projeto-labex/src/pages/TripDetailsPage/TripDetailsPage.js, modulo3/projeto-labex/projeto-labex/src/pages/TripDetailsPage/styled.js, modulo4/lista-typescript/package-lock.json, modulo4/lista-typescript/package.json, modulo4/lista-typescript/src/index.ts, modulo4/lista-typescript/src/index2.ts, modulo4/lista-typescript/src/index3.ts, modulo4/lista-typescript/src/index4.ts, modulo4/lista-typescript/src/index5.ts, modulo4/lista-typescript/src/index6.ts, modulo4/lista-typescript/src/index7.ts, modulo4/lista-typescript/src/index8.ts, modulo4/lista-typescript/src/index9.ts, modulo4/lista-typescript/tsconfig.json
=> lista de atividades de sexta-feira

modulo4/aprofundamento-express/.gitignore, modulo4/aprofundamento-express/src/index.js, modulo4/aprofundamento-express/src/index.ts, modulo4/aprofundamento-express/src/package.json, modulo4/aprofundamento-express/src/tsconfig.json, modulo4/introExpress/package-lock.json
=> inicio da atividade express

modulo4/aprofundamento-express/src/package-lock.json, modulo4/fluxo-de-dados-backend/.gitignore, modulo4/fluxo-de-dados-backend/package.json, modulo4/fluxo-de-dados-backend/src/data.ts, modulo4/fluxo-de-dados-backend/src/index.ts, modulo4/fluxo-de-dados-backend/tsconfig.json
=> iniciando atividade

modulo4/fluxo-de-dados-backend/package-lock.json, modulo4/projeto-LebeBank/.gitignore, modulo4/projeto-LebeBank/package-lock.json, modulo4/projeto-LebeBank/package.json, modulo4/projeto-LebeBank/src/accounts.ts, modulo4/projeto-LebeBank/src/index.ts, modulo4/projeto-LebeBank/src/type.ts, modulo4/projeto-LebeBank/tsconfig.json
###Projeto LabeBanck
- Buscar todas as contas;
- Criar conta;
- Ver saldo;
Pegar Conta:
Criar Conta:
=> inicio do projeto labebank- pega todas as contas

modulo4/relacoes-sql/.gitignore, modulo4/relacoes-sql/index.md
=> atividades relações de tabelas mysql

modulo4/introducao-sql/Intro-MySQL.txt
- Todas os exercícios solicitados
=> atividade de introdução ao MySQL

modulo4/Projeto-IWFS-To-Do-List/package-lock.json, modulo4/Projeto-IWFS-To-Do-List/request.rest, modulo4/knex-js/.gitignore, modulo4/knex-js/package.json, modulo4/knex-js/request.rest, modulo4/knex-js/src/connection.ts, modulo4/knex-js/src/index.md, modulo4/knex-js/src/index.ts, modulo4/knex-js/tsconfig.json
=> atividade Knex

modulo5/projeto-Labook/.gitignore, modulo5/projeto-Labook/package.json, modulo5/projeto-Labook/quest.rest, modulo5/projeto-Labook/src/data/BaseDatabase.ts, modulo5/projeto-Labook/src/data/getPostByIdDatabase.ts, modulo5/projeto-Labook/src/data/migrations.ts, modulo5/projeto-Labook/src/data/postDatabase.ts, modulo5/projeto-Labook/src/data/userDatabase.ts, modulo5/projeto-Labook/src/index.ts, modulo5/projeto-Labook/src/model/Post.ts, modulo5/projeto-Labook/src/model/User.ts, modulo5/projeto-Labook/src/services/Authenticator.ts, modulo5/projeto-Labook/src/services/HashManager.ts, modulo5/projeto-Labook/src/services/idGenerator.ts, modulo5/projeto-Labook/src/types/types.ts, modulo5/projeto-Labook/src/userBusiness/getPostByIdBusiness.ts, modulo5/projeto-Labook/src/userBusiness/postBusiness.ts, modulo5/projeto-Labook/src/userBusiness/userBusiness.ts, modulo5/projeto-Labook/src/userController/app.ts, modulo5/projeto-Labook/src/userController/getPostByIdController.ts, modulo5/projeto-Labook/src/userController/postController.ts, modulo5/projeto-Labook/src/userController/userController.ts, modulo5/projeto-Labook/tsconfig.json
=> Correção projeto
